### ISSUE TITLE
Add support for rewriting method signatures

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-upgrader#175]
I'm not sure if this is doable yet, but assuming we start adding PHP 7 type hints etc to our existing API for SilverStripe 5, it'd be nice to be able to have the upgrader automatically rewrite methods for people's child classes. For example:

```php
# SilverStripe 4: SiteTree
public function getCMSFields()

# SilverStripe 5: SiteTree
public function getCMSFields(): FieldList
```

Possible upgrader rule:
```yaml
rules:
  signature_replacements:
    SilverStripe\CMS\Model\SiteTree:
      'getCMSFields()': 'getCMSFields: FieldList'
```

It'd also need to import namespaces that may not exist yet, although I assume that `getCMSFields(): \SilverStripe\Forms\FieldList` would parse correctly when the parent's signature says `getCMSFields(): FieldList` with an imported namespace, so maybe that's a nice to have.
