### ISSUE TITLE
Feature: add classname_value_remapping

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-upgrader#35]
Would be great, if it could add a config to remap namespaced classes, similar to upgrade.yml:

```
SilverStripe\ORM\DatabaseAdmin:
  classname_value_remapping:
    MyClass: My\Namespace\MyClass
```

**Comment by maxime-rainville** [comment]
Could you elaborate a little bit on this? I'm not quite sure what you mean.

**Comment by robbieaverill** [comment]
I can help on this - for ClassName columns containing un-namespaced values in SS3 like BlogPost, this config prop will allow automatic replacement with the fully namespaced class that you define. We use this to help with upgrades. At least in the past it was a common thing to add when upgrading a module for any DataObjects, especially for page types.

**Comment by maxime-rainville** [comment]
Ok. That starting to make more sense in my little head.

So basically, we would like to update one of the existing command to create a YML file under `_config` that would add some entries to `SilverStripe\ORM\DatabaseAdmin::classname_value_remapping`.

That way, the first time the user `dev/build` their upgraded site, the `ClassName` column would get updated to the namespaced equivalent.

**Comment by TomasVotruba** [comment]
I'm starting to looking into feature that could Rector handle based #128 

Could you provide some config and differences to clsasic class rename?

At the moment it can be done like:

```yaml
services:
    Rector\Rector\Dynamic\ClassReplacerRector:
        $oldToNewClasses:
            # old class: new class
            'PHPUnit_Framework_TestCase': 'PHPUnit\Framework\TestCase'
```

or rename part of namespace

```

## better-reflection20.yml better-reflection20.yml
 servicesservices:
    :     Rector\Rector\Dynamic\NamespaceReplacerRectorRector\Rector\Dynamic\NamespaceRep :
        $oldToNewNamespaces:
            # old namespace: new namespace
            'BetterReflection': 'Roave\BetterReflection'
```

**Comment by dhensby** [comment]
@TomasVotruba so I think this is talking about values in the database. This is a bit specialised and I think unlikely to be a good starting place for rector

**Comment by TomasVotruba** [comment]
Oh, I see. You're right, this is not right place for Rector

**Comment by maxime-rainville** [comment]
The upgrader wouldn't update the DB directly. It would just add an entry to a YML file:

```yml
SilverStripe\ORM\DatabaseAdmin:
  classname_value_remapping:
    MyOldClassName: My\Namespaced\ClassName
```

When building the DB, `DatabaseAdmin` will update existing Data according to its `classname_value_remapping`.
